language: node_js
before_script: npm run build:prod
after_success:
  - ".travis/build_docker.sh"
node_js:
  - '8.6'
sudo: false
notifications:
  slack:
    rooms:
      - jembihealthsystems:mlQYVFbijxcZkesCt7G5VBoM
    on_success: change
    on_failure: always
