language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
after_success: curl -X POST -H "api_key: fdb9e03f-f843-4bea-9d02-43ab619dd289" http://162.243.219.172/deploys/openhim-console/preprod